### Get all auth records (findAll)
GET http://localhost:3000/auth
Content-Type: application/json

###

### Get auth by ID (findOne)
GET http://localhost:3000/auth/3
Content-Type: application/json

###

### Create new auth (create)
POST http://localhost:3000/auth
Content-Type: application/json

{
	"username": "testuser006",
	"password": "testpassword"
}

###

### Update auth by ID (update)
PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
	"username": "updateduser",
	"password": "updatedpassword"
}

###

### Delete auth by ID (remove)
DELETE http://localhost:3000/auth/7
Content-Type: application/json

### PUT
PUT http://localhost:3000/auth/8
Content-Type: application/json

{
	"username": "updateduser",
	"password": "updatedpassword"
}
